/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChipOption: typeof import('./src/components/controls/ChipOption.vue')['default']
    CountDown: typeof import('./src/components/playbackVis/CountDown.vue')['default']
    MeterVis: typeof import('./src/components/playbackVis/MeterVis.vue')['default']
    NmCard: typeof import('./src/components/containment/nmCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoundGeneratorControls: typeof import('./src/components/controls/SoundGeneratorControls.vue')['default']
    VolumeDialog: typeof import('./src/components/dialogs/volumeDialog.vue')['default']
  }
}
