/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BinauralBeatSynthOpsDialog: typeof import('./src/components/dialogs/binauralBeatSynthOpsDialog.vue')['default']
    ChipOption: typeof import('./src/components/controls/ChipOption.vue')['default']
    CountDown: typeof import('./src/components/playbackVis/CountDown.vue')['default']
    FftVis: typeof import('./src/components/playbackVis/fftVis.vue')['default']
    ListItemNumberInput: typeof import('./src/components/bits/ListItemNumberInput.vue')['default']
    ListItemSelectionInput: typeof import('./src/components/bits/ListItemSelectionInput.vue')['default']
    MenuList: typeof import('./src/components/containment/MenuList.vue')['default']
    MeterPlot: typeof import('./src/components/playbackVis/MeterPlot.vue')['default']
    MeterVis: typeof import('./src/components/playbackVis/MeterVis.vue')['default']
    NmCard: typeof import('./src/components/containment/nmCard.vue')['default']
    NoiseOptionsDialog: typeof import('./src/components/dialogs/noiseOptionsDialog.vue')['default']
    PlayBackProgress: typeof import('./src/components/playbackVis/PlayBackProgress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoundGeneratorControls: typeof import('./src/components/controls/SoundGeneratorControls.vue')['default']
    VolumeDialog: typeof import('./src/components/dialogs/volumeDialog.vue')['default']
    WaveFormPlot: typeof import('./src/components/playbackVis/WaveFormPlot.vue')['default']
    WaveFormVis: typeof import('./src/components/playbackVis/WaveFormVis.vue')['default']
  }
}
