/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseEventLoopCard: typeof import('./src/components/bits/BaseEventLoopCard.vue')['default']
    BinauralBeatSynthOpsDialog: typeof import('./src/components/dialogs/binauralBeatSynthOpsDialog.vue')['default']
    BinauralFftVis: typeof import('./src/components/playbackVis/BinauralFftVis.vue')['default']
    ChipOption: typeof import('./src/components/controls/ChipOption.vue')['default']
    CountDown: typeof import('./src/components/playbackVis/CountDown.vue')['default']
    EditEventLoopDialog: typeof import('./src/components/dialogs/editEventLoopDialog.vue')['default']
    EditLoopEventsDialog: typeof import('./src/components/dialogs/editLoopEventsDialog.vue')['default']
    EventEntryFilter: typeof import('./src/components/bits/EventEntryFilter.vue')['default']
    EventEntrySynth: typeof import('./src/components/bits/EventEntrySynth.vue')['default']
    EventLoopChunck: typeof import('./src/components/bits/EventLoopChunck.vue')['default']
    EventLoopEntry: typeof import('./src/components/bits/EventLoopEntry.vue')['default']
    EventLoopInfo: typeof import('./src/components/bits/EventLoopInfo.vue')['default']
    EventLoopItem: typeof import('./src/components/bits/EventLoopItem.vue')['default']
    EventSequenceEntry: typeof import('./src/components/bits/EventSequenceEntry.vue')['default']
    EventSequenceInfo: typeof import('./src/components/bits/EventSequenceInfo.vue')['default']
    FftVis: typeof import('./src/components/playbackVis/fftVis.vue')['default']
    ListItemNumberInput: typeof import('./src/components/bits/ListItemNumberInput.vue')['default']
    ListItemSelectionInput: typeof import('./src/components/bits/ListItemSelectionInput.vue')['default']
    MenuList: typeof import('./src/components/containment/MenuList.vue')['default']
    MeterPlot: typeof import('./src/components/playbackVis/MeterPlot.vue')['default']
    MeterVis: typeof import('./src/components/playbackVis/MeterVis.vue')['default']
    NmCard: typeof import('./src/components/containment/nmCard.vue')['default']
    NoiseOptionsDialog: typeof import('./src/components/dialogs/noiseOptionsDialog.vue')['default']
    OscillatorVis: typeof import('./src/components/playbackVis/oscillatorVis.vue')['default']
    PlayBackProgress: typeof import('./src/components/playbackVis/PlayBackProgress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveProgramBtnGroup: typeof import('./src/components/controls/SaveProgramBtnGroup.vue')['default']
    SoundGeneratorControls: typeof import('./src/components/controls/SoundGeneratorControls.vue')['default']
    VolumeDialog: typeof import('./src/components/dialogs/volumeDialog.vue')['default']
    WaveFormPlot: typeof import('./src/components/playbackVis/WaveFormPlot.vue')['default']
    WaveFormVis: typeof import('./src/components/playbackVis/WaveFormVis.vue')['default']
  }
}
